name: Sync Fork

on:
  workflow_dispatch:

jobs:
  sync:
     runs-on: ubuntu-latest

     permissions:
       contents: write

     steps:
       - run: ls -la
       - run: git status
       - run: git remote -v
       - run: git log --oneline
       - run: git branch -v
       
