name: Sync Fork

on:
  workflow_dispatch:

jobs:
  sync:
     runs-on: ubuntu-latest

     permissions:
       contents: write

     steps:
       - run: git clone https://github.com/skiadas/HC26-Burchett-Matt-Senior-Project.git .
       - run: git status
       - run: git remote add upstream https://github.com/Hanover-CS/HC26-Burchett-Matt-Senior-Project.git
       - run: git fetch upstream
       - run: git rebase upstream/main
       
