name: Sync Fork

on:
  workflow_dispatch:

jobs:
  sync:
     runs-on: ubuntu-latest

     permissions:
       contents: write

     steps:
       - uses: actions/checkout@v4
       - run: git status
       - run: git log --oneline
       - run: git remote add upstream https://github.com/Hanover-CS/HC26-Burchett-Matt-Senior-Project.git
       - run: git fetch upstream
       - run: git rebase upstream/main
       - run: git push --force origin main
       
