name: Sync Fork

on:
  workflow_dispatch:

jobs:
  sync:
     runs-on: ubuntu-latest

     permissions:
       contents: write

     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - run: |
           git remote add upstream https://github.com/Hanover-CS/HC26-Burchett-Matt-Senior-Project.git
           git fetch upstream
           git config user.name "github-actions[bot]"
           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git rebase upstream/main
           git push --force origin main
       
