name: Sync Fork

on:
  workflow_dispatch:

jobs:
  sync:
     runs-on: ubuntu-latest

     permissions:
       contents: write

     steps:
       - uses: actions/checkout@v4
       - uses: imba-tjd/rebase-upstream-action@master
         with:
           branch: main
       
